// Exporta los tool schemas (Anthropic Tool Use v1) usados por la cascada de
// Vigía a un `tools.json` canónico en la raíz del repo, parseable por evaluadores
// externos (ej. Bendi). Fuente de verdad = los `*Tool` const exportados por cada
// agente en `apps/web/lib/agents/*.ts`. Si un schema cambia ahí, este script lo
// regenera. NO editar `tools.json` a mano.
//
// Uso: pnpm tools:export   (o npm/yarn equivalente)

import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

import { decideActionTool } from "../lib/agents/call-triage";
import { decideVerificationOutcomeTool } from "../lib/agents/identity-verifier";
import { translateWithCitationsTool } from "../lib/agents/regulatory-translator";
import { submitAnalysisTool } from "../lib/agents/vishing-analyst";
import { submitNotificationTool } from "../lib/agents/caregiver-notifier";

type AgentToolMeta = {
  agent: string;
  source_file: string;
  model: string;
  tool_choice: { type: "tool"; name: string };
  caller: string;
};

const REGISTRY: ReadonlyArray<{
  tool: { name: string; description: string; input_schema: unknown };
  meta: AgentToolMeta;
}> = [
  {
    tool: decideActionTool,
    meta: {
      agent: "call-triage",
      source_file: "apps/web/lib/agents/call-triage.ts",
      model: "claude-sonnet-4-6",
      tool_choice: { type: "tool", name: "decide_action" },
      caller: "runCallTriage",
    },
  },
  {
    tool: decideVerificationOutcomeTool,
    meta: {
      agent: "identity-verifier",
      source_file: "apps/web/lib/agents/identity-verifier.ts",
      model: "claude-sonnet-4-6",
      tool_choice: { type: "tool", name: "decide_verification_outcome" },
      caller: "runIdentityVerifier",
    },
  },
  {
    tool: translateWithCitationsTool,
    meta: {
      agent: "regulatory-translator",
      source_file: "apps/web/lib/agents/regulatory-translator.ts",
      model: "claude-sonnet-4-6",
      tool_choice: { type: "tool", name: "translate_with_citations" },
      caller: "runRegulatoryTranslator",
    },
  },
  {
    tool: submitAnalysisTool,
    meta: {
      agent: "vishing-analyst",
      source_file: "apps/web/lib/agents/vishing-analyst.ts",
      model: "claude-opus-4-7",
      tool_choice: { type: "tool", name: "submit_analysis" },
      caller: "runVishingAnalyst",
    },
  },
  {
    tool: submitNotificationTool,
    meta: {
      agent: "caregiver-notifier",
      source_file: "apps/web/lib/agents/caregiver-notifier.ts",
      model: "claude-sonnet-4-6",
      tool_choice: { type: "tool", name: "submit_notification" },
      caller: "runCaregiverNotifier",
    },
  },
];

function assertValidAnthropicTool(t: {
  name: string;
  description: string;
  input_schema: unknown;
}): void {
  if (!t.name || typeof t.name !== "string") {
    throw new Error(`tool.name missing or not string: ${JSON.stringify(t)}`);
  }
  if (!t.description || typeof t.description !== "string") {
    throw new Error(`tool.description missing for ${t.name}`);
  }
  const s = t.input_schema as Record<string, unknown> | undefined;
  if (!s || typeof s !== "object") {
    throw new Error(`tool.input_schema missing for ${t.name}`);
  }
  if (s.type !== "object") {
    throw new Error(`tool ${t.name}: input_schema.type must be "object"`);
  }
  if (!Array.isArray(s.required)) {
    throw new Error(`tool ${t.name}: input_schema.required[] missing`);
  }
  if (!s.properties || typeof s.properties !== "object") {
    throw new Error(`tool ${t.name}: input_schema.properties missing`);
  }
}

function main(): void {
  for (const { tool } of REGISTRY) {
    assertValidAnthropicTool(tool);
  }

  const names = REGISTRY.map((r) => r.tool.name);
  const dupes = names.filter((n, i) => names.indexOf(n) !== i);
  if (dupes.length > 0) {
    throw new Error(`duplicate tool names: ${dupes.join(", ")}`);
  }

  const payload = {
    schema_version: "1.0",
    spec: "anthropic.tool_use.v1",
    generated_at: new Date().toISOString(),
    project: "vigia",
    note:
      "Generated by apps/web/scripts/export-tools.ts. DO NOT EDIT BY HAND. " +
      "Source of truth: the `*Tool` const exports in apps/web/lib/agents/*.ts. " +
      "Regenerate with `npm run tools:export` (cwd: apps/web).",
    tools: REGISTRY.map(({ tool }) => ({
      name: tool.name,
      description: tool.description,
      input_schema: tool.input_schema,
    })),
    usage: Object.fromEntries(
      REGISTRY.map(({ tool, meta }) => [tool.name, meta]),
    ),
  };

  const here = dirname(fileURLToPath(import.meta.url));
  const repoRoot = resolve(here, "..", "..", ".."); // apps/web/scripts -> apps/web -> apps -> repo
  const rootOutput = resolve(repoRoot, "tools.json");
  const appOutput = resolve(repoRoot, "apps", "web", "public", "tools.json");

  mkdirSync(dirname(appOutput), { recursive: true });

  const json = JSON.stringify(payload, null, 2) + "\n";
  writeFileSync(rootOutput, json, "utf-8");
  writeFileSync(appOutput, json, "utf-8");

  console.log(`OK ${REGISTRY.length} tools written:`);
  console.log(`  - ${rootOutput}`);
  console.log(`  - ${appOutput}  (served as /tools.json)`);
  for (const r of REGISTRY) {
    console.log(`    * ${r.tool.name}  (${r.meta.agent}, ${r.meta.model})`);
  }
}

main();
